name: Push Trigger Workflow

on:
  push:
    branches:
      - main

jobs:
  push-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Success Message
        run: echo "Workflow triggered successfully!"

      - name: Display Date and Time
        run: date

      - name: Display Current Directory
        run: pwd
