name: Basic GitHub Actions Task

on:
  push:
  workflow_dispatch:

jobs:
  basic-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Current Directory
        run: pwd

      - name: List Files
        run: ls -la

      - name: Show Date
        run: date

      - name: Create Text File
        run: |
          echo "This file was created using GitHub Actions." > output.txt
          cat output.txt

      - name: Run Python Program
        run: |
          python3 -c "print('Hello from Python!')"
